### ISSUE TITLE
Set resource requests/limits for weaviate and docker container

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate-helm#16]
At the moment, we can only set resource requests and limits for the `esvector` and `etcd` containers, but not for the other two. This should be fixed.

## Todos

* [x] add to templates
* [x] add appropriate defaults in `values.yaml`
* [x] add appropriate defaults in `values-minimal.yaml`

**Comment by etiennedi** [comment]
closed in 9.0.0.
